<?php

namespace App\GraphQL\Queries;

use GraphQL\Type\Definition\ResolveInfo;
use Nuwave\Lighthouse\Support\Contracts\GraphQLContext;

class FaseBulan
{
    /**
     * Return a value for the field.
     *
     * @param  null  $rootValue Usually contains the result returned from the parent field. In this case, it is always `null`.
     * @param  mixed[]  $args The arguments that were passed into the field.
     * @param  \Nuwave\Lighthouse\Support\Contracts\GraphQLContext  $context Arbitrary data that is shared between all fields of a single query.
     * @param  \GraphQL\Type\Definition\ResolveInfo  $resolveInfo Information about the query itself, such as the execution state, the field name, path to the field from the root, and more.
     * @return mixed
     */
    public function __invoke($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {

        return [
            'Ijtima' => [
                'HY' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['HY'],
                'K' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['K'],
                'T' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T'],
                'JD' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['JD'],
                'M' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['M'],
                'Mq' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['Mq'],
                'F' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['F'],
                'T1' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T1'],
                'T2' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T2'],
                'T3' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T3'],
                'T4' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T4'],
                'T5' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T5'],
                'T6' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T6'],
                'T7' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T7'],
                'T8' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T8'],
                'T9' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T9'],
                'T10' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T10'],
                'T11' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T11'],
                'T12' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T12'],
                'T13' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['T13'],
                'MT' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['MT'],
                'JDI' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['JDI'],
                'W1' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['W1'],
                'WD' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['WD'],
                'A' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['A'],
                'B' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['B'],
                'C' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['C'],
                'D' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['D'],
                'TGL' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['TGL'],
                'BLN' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['BLN'],
                'THN' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['THN'],
                'Hari' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['Hari'],
                'Pasaran' => ijtima($args['tahun'], $args['bulan'], 0, $args['TZ'])['Pasaran'],
            ],
            'Istiqbal' => [
                'HY' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['HY'],
                'K' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['K'],
                'T' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T'],
                'JD' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['JD'],
                'M' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['M'],
                'Mq' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['Mq'],
                'F' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['F'],
                'T1' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T1'],
                'T2' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T2'],
                'T3' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T3'],
                'T4' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T4'],
                'T5' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T5'],
                'T6' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T6'],
                'T7' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T7'],
                'T8' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T8'],
                'T9' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T9'],
                'T10' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T10'],
                'T11' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T11'],
                'T12' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T12'],
                'T13' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['T13'],
                'MT' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['MT'],
                'JDI' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['JDI'],
                'W1' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['W1'],
                'WD' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['WD'],
                'A' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['A'],
                'B' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['B'],
                'C' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['C'],
                'D' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['D'],
                'TGL' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['TGL'],
                'BLN' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['BLN'],
                'THN' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['THN'],
                'Hari' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['Hari'],
                'Pasaran' => ijtima($args['tahun'], $args['bulan'], 0.5, $args['TZ'])['Pasaran'],
            ],
            'firstQuarter' => [
                'HY' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['HY'],
                'K' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['K'],
                'T' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T'],
                'JD' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['JD'],
                'M' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['M'],
                'Mq' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['Mq'],
                'F' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['F'],
                'T1' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T1'],
                'T2' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T2'],
                'T3' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T3'],
                'T4' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T4'],
                'T5' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T5'],
                'T6' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T6'],
                'T7' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T7'],
                'T8' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T8'],
                'T9' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T9'],
                'T10' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T10'],
                'T11' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T11'],
                'T12' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T12'],
                'T13' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T13'],
                'T14' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T14'],
                'T15' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['T15'],
                'MT' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['MT'],
                'JDI' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['JDI'],
                'W1' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['W1'],
                'WD' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['WD'],
                'A' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['A'],
                'B' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['B'],
                'C' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['C'],
                'D' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['D'],
                'TGL' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['TGL'],
                'BLN' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['BLN'],
                'THN' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['THN'],
                'Hari' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['Hari'],
                'Pasaran' => quarter($args['tahun'], $args['bulan'], 0.75, $args['TZ'])['Pasaran'],
            ],
            'lastQuarter' => [
                'HY' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['HY'],
                'K' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['K'],
                'T' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T'],
                'JD' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['JD'],
                'M' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['M'],
                'Mq' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['Mq'],
                'F' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['F'],
                'T1' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T1'],
                'T2' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T2'],
                'T3' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T3'],
                'T4' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T4'],
                'T5' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T5'],
                'T6' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T6'],
                'T7' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T7'],
                'T8' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T8'],
                'T9' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T9'],
                'T10' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T10'],
                'T11' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T11'],
                'T12' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T12'],
                'T13' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T13'],
                'T14' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T14'],
                'T15' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['T15'],
                'MT' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['MT'],
                'JDI' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['JDI'],
                'W1' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['W1'],
                'WD' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['WD'],
                'A' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['A'],
                'B' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['B'],
                'C' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['C'],
                'D' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['D'],
                'TGL' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['TGL'],
                'BLN' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['BLN'],
                'THN' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['THN'],
                'Hari' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['Hari'],
                'Pasaran' => quarter($args['tahun'], $args['bulan'], 0.25, $args['TZ'])['Pasaran'],
            ],
        ];
    }
}
